# Generated by Django 5.0.6 on 2024-06-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_alter_candidate_marital_status_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Hybrid', 'Hybrid'), ('Remote', 'Remote'), ('In-Office', 'In-Office')], max_length=50),
        ),
    ]
