# Generated by Django 5.0.6 on 2024-06-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Widowed', 'Widowed'), ('Single', 'Single')], default='Single', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('In-Office', 'In-Office'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=50),
        ),
    ]
