# Generated by Django 3.2.16 on 2024-05-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0020_auto_20240525_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='education',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='work_experience',
            field=models.CharField(max_length=300),
        ),
    ]
