# Generated by Django 3.2.16 on 2024-05-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0021_auto_20240525_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='relevance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendedapplicant',
            name='relevance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
