# Generated by Django 3.2.16 on 2024-05-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0022_auto_20240526_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendedapplicant',
            name='age',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
