# Generated by Django 3.2.16 on 2024-05-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0023_auto_20240526_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendedapplicant',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
