# Generated by Django 3.2.16 on 2024-05-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0024_auto_20240527_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='reason_for_leaving',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
