# Generated by Django 3.2.16 on 2024-05-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0025_candidate_reason_for_leaving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='education',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='work_experience',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
