# Generated by Django 3.2.16 on 2024-05-30 10:00

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0027_alter_candidate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='photo',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
