# Generated by Django 3.2.16 on 2024-06-01 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0028_job_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='photo',
            new_name='image',
        ),
    ]
