# Generated by Django 3.2.16 on 2024-06-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0029_rename_photo_job_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='employee_relevance_score',
        ),
    ]
