# Generated by Django 3.2.16 on 2024-06-03 19:05

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0032_remove_candidate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
