# Generated by Django 3.2.16 on 2024-06-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0033_candidate_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='image',
        ),
    ]
