# Generated by Django 3.2.16 on 2024-06-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0035_candidate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Hybrid', 'Hybrid'), ('In-Office', 'In-Office'), ('Remote', 'Remote')], max_length=50),
        ),
    ]
