# Generated by Django 3.2.16 on 2024-06-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0036_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Hybrid', 'Hybrid'), ('In-Office', 'In-Office'), ('Remote', 'Remote')], max_length=50),
        ),
    ]
