# Generated by Django 5.0.6 on 2024-06-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0041_rename_education_candidate_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('In-Office', 'In-Office'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], max_length=50),
        ),
    ]
